- id: '1663357887700'
  alias: Ampel all on
  description: ''
  trigger: []
  condition: []
  action:
  - service: rest_command.ampel_all_on
    data: {}
  mode: single
- id: '1663358120737'
  alias: Ampel all off
  description: ''
  trigger: []
  condition: []
  action:
  - service: rest_command.ampel_off
    data: {}
  mode: single
- id: '1663362768451'
  alias: Alles-Aus-Knopf
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tasmota_5
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.new_scene
    metadata: {}
  - service: rest_command.ampel_off
    data: {}
  - service: shell_command.jukebox_suspend
    data: {}
  mode: single
- id: '1663369771702'
  alias: Labor-Status-Knopf
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tasmota_40f520cf460d_switch_relay_2
  condition: []
  action:
  - if:
    - condition: device
      type: is_on
      device_id: d1aaa3538c22db1672ebb37023c02f9b
      entity_id: switch.tasmota_40f520cf460d_switch_relay_2
      domain: switch
      for:
        hours: 0
        minutes: 0
        seconds: 0
    then:
    - service: rest_command.labor_close
      data: {}
    else:
    - service: rest_command.labor_open
      data: {}
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.raumstatus
  mode: single
- id: '1663699840830'
  alias: Labor-Status Poll
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.raumstatus
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 30
      milliseconds: 0
  - if:
    - condition: state
      entity_id: sensor.raumstatus
      attribute: open
      state: true
      for:
        hours: 0
        minutes: 1
        seconds: 20
    then:
    - type: turn_off
      device_id: d1aaa3538c22db1672ebb37023c02f9b
      entity_id: switch.tasmota_40f520cf460d_switch_relay_2
      domain: switch
    else: []
  - if:
    - condition: state
      entity_id: sensor.raumstatus
      attribute: open
      state: false
      for:
        hours: 0
        minutes: 1
        seconds: 20
    then:
    - type: turn_on
      device_id: d1aaa3538c22db1672ebb37023c02f9b
      entity_id: switch.tasmota_40f520cf460d_switch_relay_2
      domain: switch
  mode: single
- id: '1665517172017'
  alias: Raumstatus Closed
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.raumstatus
    attribute: open
    from: true
    to: false
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: Das Labor ist jetzt zu.
  mode: single
- id: '1665517334695'
  alias: Raumstatus Opened
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.raumstatus
    attribute: open
    from: false
    to: true
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: Das Labor ist jetzt offen.
  mode: single
- id: '1665525392900'
  alias: Wake Jukebox
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: d1aaa3538c22db1672ebb37023c02f9b
    entity_id: switch.tasmota_40f520cf460d_switch_relay_1
    domain: switch
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: d0:27:88:b2:48:38
  mode: single
