
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#logger:
#  default: debug

# Example configuration.yaml entry
switch:
  - platform: command_line
    switches:
      frozenbottle_patterns:
        command_on: "ssh frozen-bottle systemctl start frozen-bottle-loop-all.service"
        command_off: "ssh frozen-bottle systemctl stop frozen-bottle-loop-all.service"

  - platform: wake_on_lan
    mac: "d0:27:88:b2:48:38"
    name: "Jukebox"

  - platform: template
    switches:
      jukebox_mute:
        turn_on:
          service: shell_command.jukebox_mute
        turn_off:
          service: shell_command.jukebox_unmute

      jukebox_visualizer:
        turn_on:
          service: shell_command.frozen_bottle_jukebox_visualizer_start
        turn_off:
          service: shell_command.frozen_bottle_jukebox_visualizer_stop

rest_command:
  ampel_off:
    url: "http://ampel/stop"

  ampel_normal:
    url: "http://ampel/normal"

  ampel_night:
    url: "http://ampel/night"

  ampel_red:
    url: "http://ampel/custom"
    method: post
    content_type: "application/x-www-form-urlencoded"
    payload: "red=1&yellow=0&green=0"

  ampel_yellow:
    url: "http://ampel/custom"
    method: post
    content_type: "application/x-www-form-urlencoded"
    payload: "red=0&yellow=1&green=0"

  ampel_green:
    url: "http://ampel/custom"
    method: post
    content_type: "application/x-www-form-urlencoded"
    payload: "red=0&yellow=0&green=1"

  ampel_all_on:
    url: "http://ampel/custom"
    method: post
    content_type: "application/x-www-form-urlencoded"
    payload: "red=1&yellow=1&green=1"

  labor_open:
    url: "https://freieslabor.org/api/room/"
    method: post
    content_type: "application/x-www-form-urlencoded"
    payload: "open=true"
    username: "info-display"
    password: !secret labor_api
    verify_ssl: False

  labor_close:
    url: "https://freieslabor.org/api/room/"
    method: post
    content_type: "application/x-www-form-urlencoded"
    payload: "open=false"
    username: "info-display"
    password: !secret labor_api
    verify_ssl: False

shell_command:
  jukebox_spotify_next: "ssh {{ (states('sensor.jukebox_active_user') | from_json()).user }}@jukebox dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next"
  frozen_bottle_jukebox_visualizer_start: "ssh {{ (states('sensor.jukebox_active_user') | from_json()).user }}@jukebox systemctl --user start frozen-bottle-visualizer.service"
  frozen_bottle_jukebox_visualizer_stop: "ssh {{ (states('sensor.jukebox_active_user') | from_json()).user }}@jukebox systemctl --user stop frozen-bottle-visualizer.service"
  jukebox_mute: "ssh {{ (states('sensor.jukebox_active_user') | from_json()).user }}@jukebox amixer set Master mute"
  jukebox_unmute: "ssh {{ (states('sensor.jukebox_active_user') | from_json()).user }}@jukebox amixer set Master unmute"

# Example configuration.yaml entry
rest:
  - authentication: basic
    username: "info-display"
    password: !secret labor_api
    scan_interval: 100
    resource: "https://freieslabor.org/api/room/"
    verify_ssl: false
    sensor:
      - name: "Raumstatus"
        json_attributes:
          - "open"
          - "since"

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_token
    allowed_chat_ids:
      - -1001326646611 # Freies Labor Channel
